# Generated by Django 4.1.3 on 2022-12-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='answer',
            field=models.ManyToManyField(null=True, to='testing.answers'),
        ),
    ]
